#!/bin/bash

options=(
  style=round
  width=6.0
  hidpi=off
  active_color=0xc0e2e2e3    # Active window border (visible)
  inactive_color=0x00000000   # Fully transparent (no border)
  background_color=0x302c2e34 # Optional: subtle background hint
)

borders "${options[@]}"
